-- Intentionally empty: this duplicate was marked applied without executing SQL.
-- Incident is created by 20260810161453_add_incident_management instead.
-- Keep this migration name so existing database history remains continuous.
-- Existing databases: see docs/incident-migration-repair.md before migrating.
